# Generated by Django 5.1.6 on 2025-02-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0005_rename_pago_documentoestudiante_boucher_pago_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='boucher_pago_1',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='boucher_pago_2',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='copia_bachiller_1',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='copia_bachiller_2',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='declaracion_jurada',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='estado_boucher_pago_1',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='estado_boucher_pago_2',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='estado_copia_bachiller_1',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='estado_copia_bachiller_2',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='estado_declaracion_jurada',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='estado_solicitud_1',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='estado_solicitud_2',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='estado_tesis',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='solicitud_1',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='solicitud_2',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='tesis',
        ),
    ]
