# Generated by Django 5.1.6 on 2025-02-26 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('modalidad_1', 'Modalidad 1'), ('modalidad_2', 'Modalidad 2')], max_length=20)),
                ('dni', models.FileField(upload_to='documentos/dni/')),
                ('pago', models.FileField(upload_to='documentos/pago/')),
                ('tesis', models.FileField(upload_to='documentos/tesis/')),
                ('declaracion_jurada', models.FileField(blank=True, null=True, upload_to='documentos/declaracion_jurada/')),
                ('copia_bachiller_1', models.FileField(upload_to='documentos/copia_bachiller/')),
                ('boucher_pago_1', models.FileField(upload_to='documentos/boucher_pago/')),
                ('copia_bachiller_2', models.FileField(blank=True, null=True, upload_to='documentos/copia_bachiller/')),
                ('boucher_pago_2', models.FileField(blank=True, null=True, upload_to='documentos/boucher_pago/')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
