# Generated by Django 5.1.6 on 2025-02-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentoestudiante',
            old_name='dni',
            new_name='dni_1',
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='carrera',
            field=models.CharField(choices=[('Derecho', 'Derecho'), ('Ing. Sistemas', 'Ing. Sistemas'), ('Agronomía', 'Agronomía'), ('Veterinaria', 'Veterinaria')], default='Selecciona tu carrera', max_length=50),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='dni_2',
            field=models.FileField(blank=True, null=True, upload_to='documentos/dni/'),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='solicitud_1',
            field=models.FileField(blank=True, null=True, upload_to='documentos/solicitudes/'),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='solicitud_2',
            field=models.FileField(blank=True, null=True, upload_to='documentos/solicitudes/'),
        ),
    ]
