# Generated by Django 5.1.6 on 2025-03-29 21:45

import app_titulacion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulacion_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('tesis', 'Tesis'), ('declaracion_jurada', 'Declaración Jurada'), ('copia_bachiller', 'Copia de Bachiller'), ('boucher_pago', 'Boucher de Pago'), ('solicitud', 'Solicitud')], max_length=50)),
                ('archivo', models.FileField(upload_to=app_titulacion.models.estudiante_directory_path)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_subida'],
                'unique_together': {('user', 'tipo_documento', 'version')},
            },
        ),
        migrations.DeleteModel(
            name='DocumentoEstudiante',
        ),
    ]
