# Generated by Django 5.1.6 on 2025-02-27 18:16

import app_titulacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0002_rename_dni_documentoestudiante_dni_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoestudiante',
            name='boucher_pago_1',
            field=models.FileField(upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='boucher_pago_2',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='copia_bachiller_1',
            field=models.FileField(upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='copia_bachiller_2',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='declaracion_jurada',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='dni_1',
            field=models.FileField(upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='dni_2',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='pago',
            field=models.FileField(upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='solicitud_1',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='solicitud_2',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AlterField(
            model_name='documentoestudiante',
            name='tesis',
            field=models.FileField(upload_to=app_titulacion.models.estudiante_directory_path),
        ),
    ]
