# Generated by Django 5.1.6 on 2025-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0003_alter_documentoestudiante_boucher_pago_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='boucher_pago_1',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='boucher_pago_2',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='copia_bachiller_1',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='copia_bachiller_2',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='solicitud_1',
        ),
        migrations.RemoveField(
            model_name='documentoestudiante',
            name='solicitud_2',
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_declaracion_jurada',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_dni_1',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_dni_2',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_tesis',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
    ]
