# Generated by Django 5.1.6 on 2025-04-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0004_alter_expediente_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('observado', 'Observado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='en_proceso', max_length=20),
        ),
        migrations.DeleteModel(
            name='Titulacion_Individual',
        ),
    ]
