# Generated by Django 5.1.6 on 2025-04-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0005_alter_expediente_estado_delete_titulacion_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('observado', 'Observado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='en_proceso', max_length=20),
        ),
    ]
