# Generated by Django 5.1.6 on 2025-04-02 01:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0006_alter_expediente_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='DNI debe contener 8 dígitos', regex='^\\d{8}$')])),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Teléfono debe contener 9 dígitos', regex='^\\d{9}$')])),
                ('correo_institucional', models.EmailField(help_text='Correo institucional del docente', max_length=254, unique=True)),
                ('codigo_doctor', models.CharField(help_text='Código único de identificación como doctor', max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['apellido_paterno', 'apellido_materno'],
            },
        ),
    ]
