# Generated by Django 5.1.6 on 2025-04-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0008_administrativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='codigo_doctor',
            field=models.CharField(blank=True, help_text='Código único de identificación como doctor (opcional)', max_length=20, null=True, unique=True),
        ),
    ]
