# Generated by Django 5.1.6 on 2025-03-05 17:36

import app_titulacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0008_alter_documentoestudiante_carrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_tesis',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='tesis',
            field=models.FileField(default='pendiente', upload_to=app_titulacion.models.estudiante_directory_path),
            preserve_default=False,
        ),
    ]
