# Generated by Django 5.1.6 on 2025-03-05 17:41

import app_titulacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0009_documentoestudiante_estado_tesis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoestudiante',
            name='tesis',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
    ]
