# Generated by Django 5.1.6 on 2025-04-03 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0009_alter_docente_codigo_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_asesorados', to='app_titulacion.docente'),
        ),
    ]
