# Generated by Django 5.1.6 on 2025-03-05 18:15

import app_titulacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_titulacion', '0010_alter_documentoestudiante_tesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoestudiante',
            name='boucher_pago_1',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='boucher_pago_2',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='copia_bachiller_1',
            field=models.FileField(blank=True, default='', null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='copia_bachiller_2',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='declaracion_jurada',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_boucher_pago_1',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_boucher_pago_2',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_copia_bachiller_1',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_copia_bachiller_2',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_declaracion_jurada',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_solicitud_1',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estado_solicitud_2',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('corregir', 'Requiere Corrección')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='solicitud_1',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='solicitud_2',
            field=models.FileField(blank=True, null=True, upload_to=app_titulacion.models.estudiante_directory_path),
        ),
    ]
